name: CI/CD Pipeline

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: school_management_test
        ports:
          - 5433:5432
    env:
      ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_pgsql
      - name: Install DBAL
        run: composer require doctrine/dbal

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Set database URL environment variable
        env:
          DATABASE_URL: postgresql://postgres:@localhost:5432/school_management_test
        run: |
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV

      - name: Set up database
        run: |
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run tests
        run: vendor/bin/phpunit --verbose